# Generated by Django 4.1.2 on 2023-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ManyToManyField(blank=True, to='post.semester'),
        ),
    ]
