# Generated by Django 4.1.2 on 2023-04-19 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_course_semester_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_post',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
